### ISSUE TITLE
Can achieve similar caddy function?

### ISSUE THREAD

**Issue by zuohuadong** [abiosoft/caddyplug#3]
like https://caddyserver.com/download

use https://www.travis-ci.org to build

and upload it in CDN

**Comment by abiosoft** [comment]
Of course you can.

If you are willing to take advantage of docker, the two lines of command below is probably the easiest way.
```
docker build -t mycaddy --build-arg plugins=git,filemanager github.com/abiosoft/caddy-docker.git
docker run -it -v `pwd`:/tmpdir --entrypoint sh mycaddy -c "cp /usr/bin/caddy /tmpdir"
```
You should have `caddy` in your current directory afterwards.

The other option is to use the technique I used in the [Dockerfile](https://github.com/abiosoft/caddy-docker/blob/10bf797de082046df8da36a4f532a8c970eddbb9/Dockerfile#L12-L33).

**Comment by abiosoft** [comment]
This is an even easier way.
https://github.com/abiosoft/caddy-docker/blob/master/BUILDER.md
