### ISSUE TITLE
I hope to provide automatic compilation.

### ISSUE THREAD

**Issue by zuohuadong** [abiosoft/caddyplug#4]
like..
```
https://caddyserver.com/download/linux/amd64?plugins=dns,http.jwt,http.realip,net


curl https://getcaddy.com | bash -s dns,http.jwt,http.realip,net
```

We can use Travis-CI automatically generated.

Then I can provide a small server.

**Comment by abiosoft** [comment]
I will be be closing this. You may want to look at https://github.com/abiosoft/caddy-docker/blob/master/BUILDER.md if that helps.
