### ISSUE TITLE
New Caddy plugin type: Caddyfile Loaders

### ISSUE THREAD

**Issue by dhaavi** [abiosoft/caddyplug#5]
Caddy now features a new plugin type that has its first awesome plugin:

> Caddy Docker Proxy:
> https://github.com/lucaslorentz/caddy-docker-proxy/
> tl;dr: Docker containers configure their own reverse proxy.

Are you planning on supporting this new plugin type?

Last lines of failed build log:
```
plugin not found
github.com/mholt/caddy/vendor/github.com/flynn/go-shlex
github.com/mholt/caddy/caddyfile
github.com/mholt/caddy
plugin not found
Cloning into '/go/src/github.com/caddyserver/builds'...
caddymain/run.go:34:2: 
../caddyhttp/docker.go:2:10: invalid import path: ""
2018/05/04 13:31:11 exit status 1
exit status 1
The command '/bin/sh -c VERSION=${version} PLUGINS=${plugins} /bin/sh /usr/bin/builder.sh' returned a non-zero code: 1
```

**Comment by abiosoft** [comment]
Yeah I'm aware, there's also an issue opened https://github.com/abiosoft/caddy-docker/issues/109 for the docker image.

I will leave both open until it is addressed.

**Comment by abiosoft** [comment]
Fixed. Try again using `docker` as plugin name.

**Comment by dhaavi** [comment]
Great! It works... mostly. I have encountered a strange issue [described here](https://github.com/lucaslorentz/caddy-docker-proxy/issues/33), but do not think that it is related to the build - but who can know anything for sure at this level of strangeness.
